function [AircraftModel] = InitializeAircraftModel(modelpath, modeltype)
% =========================================================================
% function: InitalizeAircraftModel() 
% Author: Ariel Walter, Ph.D. - Reisident Engineer
%         email: awalter@systemstech.com
%
% Copyright (c) Systems Technology, Inc.
% =========================================================================
%     
% -------------------------------------------------------------------------
% REVISIONS:
% 2026.27.02 (A. Walter) - Initial
% -------------------------------------------------------------------------

switch modeltype
    case 'RMAC'
        % =========================================================================
        % Load model; Generated by running LinearizeJohnnySweep.m
        % -------------------------------------------------------------------------
        tmp = load(modelpath);
        %RMAC Aircraft configuration
        AircraftModel.AircraftInfo = tmp.Aircraft;
        % Bare Airframe Dynamics, 
        AircraftModel.BareAirframeDynamics = tmp.BareAirframeSys;
        % Default Mixing Matrix
        AircraftModel.Mixer = tmp.Mixer;
        % Trim points defined by forward flight speed
        AircraftModel.TrimSpeeds = tmp.FFSpeeds;
        % Trim Inputs
        AircraftModel.TrimInputs = tmp.u_trim;
        % Trim States
        AircraftModel.TrimStates = tmp.x_trim;
        % Trim Outputs 
        % Initailize for scaling of PWM signal
        Kv = 1750; % Motor Constant, RPM/V
        AircraftModel.MaxOmegaLimit = ones(4,1)*Kv*25*pi/30*0.81;
        AircraftModel.MinOmegaLimit = zeros(4,1);
        AircraftModel.MaxPWMLimit = 2000;
        AircraftModel.MinPWMLimit = 1000;
        % load hover Model
        AircraftModel.HoverA = tmp.BareAirframeSys{1}.A;
        AircraftModel.HoverB = tmp.BareAirframeSys{1}.B;
        AircraftModel.HoverC = tmp.BareAirframeSys{1}.C;
        AircraftModel.HoverD = tmp.BareAirframeSys{1}.D;
        AircraftModel.WithMixer = tmp.AircraftWithMixer;
    otherwise
        error('Currently on supports RMAC model type')
end

end