[AircraftModel] = InitalizeAircraftModel(modelpath, modeltype)
% =========================================================================
% function: InitalizeAircraftModel() 
% Author: Ariel Walter, Ph.D. - Reisident Engineer
%         email: dmusso@systemstech.com
%
% Copyright (c) Systems Technology, Inc.
% =========================================================================
%     
% -------------------------------------------------------------------------
% REVISIONS:
% 2026.27.02 (A. Walter) - Initial
% -------------------------------------------------------------------------

switch modeltype
    case 'RMAC'
        % =========================================================================
        % Load model; Generated by running LinearizeJohnnySweep.m
        % -------------------------------------------------------------------------
            tmp = load(modelpath);
            %RMAC Aircraft configuration
            AircraftModel.AircraftInfo = tmp.Aircraft;
            % Bare Airframe Dynamics, currently only state space form is
            % supported
            AircraftModel.BareAirframeDynamics = tmp.BareAirframeSys;
            % Default Mixing Matrix
            AircraftModel.Mixer = tmp.Mixer;
            % Trim points defined by forward flight speed (sim currently only supports hover)
            AircraftModel.TrimSpeeds = tmp.FFSpeeds;
            % Trim Inputs
            AircraftModel.TrimInputs = tmp.u_trim;
            % Trim States
            AircraftModel.TrimStates = tmp.x_trim;

    otherwise
        error('Currently on supports RMAC model type')
end


end